version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secure_register
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./SecureRegisterWebSiteBack
    container_name: backend_node_ts
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: secure_register

  frontend:
    build: ./SecureRegisterWebsiteFront
    container_name: frontend_flask
    ports:
      - "5000:5000"
    depends_on:
      - backend

volumes:
  db_data:
